package com.facebook.video.heroplayer.setting;

import X.C32232Ax;
import ch.boye.httpclientandroidlib.HttpStatus;
import java.io.Serializable;

public class FbAutogeneratedSettings implements Serializable {
    public static final long serialVersionUID = 968006291006349357L;
    public final int autoAddIntParams;
    public final boolean enableSloHttpHeaderLogging;
    public final String grootPrefetchSuboriginBlocklist;
    public final int maxAllowed503RetryCount;

    public FbAutogeneratedSettings() {
        this.autoAddIntParams = HttpStatus.SC_SWITCHING_PROTOCOLS;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = "";
    }

    public FbAutogeneratedSettings(C32232Ax r2) {
        this.autoAddIntParams = HttpStatus.SC_SWITCHING_PROTOCOLS;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = "";
    }
}
