package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import java.util.Locale;

/* renamed from: X.4k9  reason: invalid class name */
public final class AnonymousClass4k9 extends C02220Ah implements AnonymousClass0YY {
    public static final AnonymousClass4k9 A00 = new AnonymousClass4k9();

    public AnonymousClass4k9() {
        super(1);
    }

    public final /* bridge */ /* synthetic */ Object invoke(Object obj) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) obj;
        C04220Ms.A0B(autoGeneratedCardType, 0);
        return C18190wL.A0r(Locale.ROOT, autoGeneratedCardType.A00);
    }
}
