package X;

/* renamed from: X.2AQ  reason: invalid class name */
public enum AnonymousClass2AQ implements C81604o4 {
    ADD_PHONE,
    FB_CONNECT,
    CONTACT_INVITE,
    ACCOUNT_PRIVACY,
    TAKE_PROFILE_PHOTO,
    TURN_ON_ONETAP,
    CHECK_FOR_PHONE,
    CHECK_FOR_EMAIL,
    ADD_EMAIL,
    DISCOVER_PEOPLE,
    BASED_ON_YOUR_INTERESTS,
    DISCOVER_ACCOUNTS,
    FOLLOW_FROM_LOGGED_IN_ACCOUNTS,
    CREATE_PASSWORD,
    IDENTITY_SYNCING,
    IDENTITY_SYNCING_AFTER_NUX_LINKING,
    LIGHTWEIGHT_CONNECTIONS,
    AUTO_CROSSPOSTING,
    PUSH_OPT_IN,
    UNKNOWN
}
