package X;

/* renamed from: X.2AC  reason: invalid class name */
public enum AnonymousClass2AC implements C021109v {
    IG_FEED_COMPOSER_ADVANCED_SETTINGS_TOGGLE_ENABLE("IG_FEED_COMPOSER_ADVANCED_SETTINGS_TOGGLE_ENABLE"),
    IG_FEED_COMPOSER_ADVANCED_SETTINGS_TOGGLE_ENABLE_POST_ACCOUNT_LINK("IG_FEED_COMPOSER_ADVANCED_SETTINGS_TOGGLE_ENABLE_POST_ACCOUNT_LINK"),
    IG_FEED_COMPOSER_SHARE_TO_FACEBOOK_TOGGLE_ENABLE("IG_FEED_COMPOSER_SHARE_TO_FACEBOOK_TOGGLE_ENABLE"),
    IG_FEED_COMPOSER_SHARE_TO_FACEBOOK_TOGGLE_ENABLE_POST_ACCOUNT_LINK("IG_FEED_COMPOSER_SHARE_TO_FACEBOOK_TOGGLE_ENABLE_POST_ACCOUNT_LINK"),
    IG_FEED_COMPOSER_SHARE_TO_FACEBOOK_TOGGLE_TOOLTIP("IG_FEED_COMPOSER_SHARE_TO_FACEBOOK_TOGGLE_TOOLTIP"),
    IG_SELF_STORY_VIEW_FB_BUTTON("IG_SELF_STORY_VIEW_FB_BUTTON"),
    IG_SELF_STORY_VIEW_FB_BUTTON_POST_ACCOUNT_LINK("IG_SELF_STORY_VIEW_FB_BUTTON_POST_ACCOUNT_LINK"),
    IG_SELF_STORY_VIEW_FB_BUTTON_TOOLTIP("IG_SELF_STORY_VIEW_FB_BUTTON_TOOLTIP"),
    IG_STORY_COMPOSER_YOUR_STORY_BUTTON("IG_STORY_COMPOSER_YOUR_STORY_BUTTON"),
    IG_STORY_COMPOSER_YOUR_STORY_BUTTON_TOOLTIP("IG_STORY_COMPOSER_YOUR_STORY_BUTTON_TOOLTIP"),
    IG_STORY_SETTINGS_MAIN_CAMERA_SETTINGS_BUTTON("IG_STORY_SETTINGS_MAIN_CAMERA_SETTINGS_BUTTON"),
    IG_STORY_SETTINGS_MAIN_CAMERA_SETTINGS_BUTTON_POST_ACCOUNT_LINK("IG_STORY_SETTINGS_MAIN_CAMERA_SETTINGS_BUTTON_POST_ACCOUNT_LINK"),
    IG_STORY_SHARE_SHEET_SHARE_BUTTON("IG_STORY_SHARE_SHEET_SHARE_BUTTON"),
    IG_STORY_SHARE_SHEET_SHARING_OPTIONS("IG_STORY_SHARE_SHEET_SHARING_OPTIONS");
    
    public final String A00;

    public static AnonymousClass2AC A00(String str, String str2, int i) {
        return new AnonymousClass2AC(str, i, str2);
    }

    /* access modifiers changed from: public */
    AnonymousClass2AC(String str) {
        this.A00 = str;
    }
}
