package X;

import androidx.compose.ui.Modifier;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S3200000_I2;
import com.instagram.common.typedurl.ImageUrl;
import kotlin.Unit;

/* renamed from: X.8UW  reason: invalid class name */
public final class AnonymousClass8UW extends C02220Ah implements AnonymousClass0YP {
    public final /* synthetic */ int A00;
    public final /* synthetic */ int A01;
    public final /* synthetic */ int A02;
    public final /* synthetic */ int A03;
    public final /* synthetic */ int A04;
    public final /* synthetic */ int A05;
    public final /* synthetic */ C81784oM A06;
    public final /* synthetic */ Modifier A07;
    public final /* synthetic */ AnonymousClass7HD A08;
    public final /* synthetic */ KtCSuperShape0S3200000_I2 A09;
    public final /* synthetic */ C89935Hp A0A;
    public final /* synthetic */ ImageUrl A0B;
    public final /* synthetic */ String A0C;
    public final /* synthetic */ String A0D;
    public final /* synthetic */ AnonymousClass0ZU A0E;
    public final /* synthetic */ AnonymousClass0ZU A0F;
    public final /* synthetic */ AnonymousClass0ZU A0G;
    public final /* synthetic */ AnonymousClass0ZU A0H;
    public final /* synthetic */ AnonymousClass0ZU A0I;
    public final /* synthetic */ AnonymousClass0ZU A0J;
    public final /* synthetic */ AnonymousClass0ZU A0K;
    public final /* synthetic */ AnonymousClass0YY A0L;
    public final /* synthetic */ AnonymousClass0YY A0M;
    public final /* synthetic */ AnonymousClass0YY A0N;
    public final /* synthetic */ AnonymousClass0YY A0O;
    public final /* synthetic */ AnonymousClass0YY A0P;
    public final /* synthetic */ AnonymousClass0YY A0Q;
    public final /* synthetic */ AnonymousClass0YY A0R;
    public final /* synthetic */ AnonymousClass0YP A0S;
    public final /* synthetic */ AnonymousClass8s2 A0T;
    public final /* synthetic */ boolean A0U;
    public final /* synthetic */ boolean A0V;
    public final /* synthetic */ boolean A0W;
    public final /* synthetic */ boolean A0X;
    public final /* synthetic */ boolean A0Y;
    public final /* synthetic */ boolean A0Z;
    public final /* synthetic */ boolean A0a;
    public final /* synthetic */ boolean A0b;
    public final /* synthetic */ boolean A0c;

    /* JADX INFO: super call moved to the top of the method (can break code semantics) */
    public AnonymousClass8UW(C81784oM r2, Modifier modifier, AnonymousClass7HD r4, KtCSuperShape0S3200000_I2 ktCSuperShape0S3200000_I2, C89935Hp r6, ImageUrl imageUrl, String str, String str2, AnonymousClass0ZU r10, AnonymousClass0ZU r11, AnonymousClass0ZU r12, AnonymousClass0ZU r13, AnonymousClass0ZU r14, AnonymousClass0ZU r15, AnonymousClass0ZU r16, AnonymousClass0YY r17, AnonymousClass0YY r18, AnonymousClass0YY r19, AnonymousClass0YY r20, AnonymousClass0YY r21, AnonymousClass0YY r22, AnonymousClass0YY r23, AnonymousClass0YP r24, AnonymousClass8s2 r25, int i, int i2, int i3, int i4, int i5, int i6, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9) {
        super(2);
        this.A0D = str;
        this.A0B = imageUrl;
        this.A0c = z;
        this.A08 = r4;
        this.A0U = z2;
        this.A0b = z3;
        this.A0O = r17;
        this.A0V = z4;
        this.A0E = r10;
        this.A0W = z5;
        this.A0F = r11;
        this.A0a = z6;
        this.A0X = z7;
        this.A0Z = z8;
        this.A06 = r2;
        this.A0H = r12;
        this.A0L = r18;
        this.A0J = r13;
        this.A0K = r14;
        this.A0G = r15;
        this.A0P = r19;
        this.A0R = r20;
        this.A0I = r16;
        this.A0S = r24;
        this.A0T = r25;
        this.A09 = ktCSuperShape0S3200000_I2;
        this.A0A = r6;
        this.A07 = modifier;
        this.A0Y = z9;
        this.A0C = str2;
        this.A0M = r21;
        this.A0Q = r22;
        this.A0N = r23;
        this.A00 = i;
        this.A01 = i2;
        this.A02 = i3;
        this.A03 = i4;
        this.A04 = i5;
        this.A05 = i6;
    }

    public final /* bridge */ /* synthetic */ Object invoke(Object obj, Object obj2) {
        C147188nY A0H2 = C86104wH.A0H(obj, obj2);
        String str = this.A0D;
        ImageUrl imageUrl = this.A0B;
        boolean z = this.A0c;
        AnonymousClass7HD r56 = this.A08;
        boolean z2 = this.A0U;
        boolean z3 = this.A0b;
        AnonymousClass0YY r24 = this.A0O;
        boolean z4 = this.A0V;
        AnonymousClass0ZU r25 = this.A0E;
        boolean z5 = this.A0W;
        AnonymousClass0ZU r26 = this.A0F;
        boolean z6 = this.A0a;
        boolean z7 = this.A0X;
        boolean z8 = this.A0Z;
        C81784oM r18 = this.A06;
        AnonymousClass0ZU r27 = this.A0H;
        AnonymousClass0YY r17 = this.A0L;
        AnonymousClass0ZU r28 = this.A0J;
        AnonymousClass0ZU r29 = this.A0K;
        AnonymousClass0ZU r15 = this.A0G;
        AnonymousClass0YY r14 = this.A0P;
        AnonymousClass0YY r13 = this.A0R;
        AnonymousClass0ZU r12 = this.A0I;
        AnonymousClass0YP r11 = this.A0S;
        AnonymousClass8s2 r10 = this.A0T;
        KtCSuperShape0S3200000_I2 ktCSuperShape0S3200000_I2 = this.A09;
        C89935Hp r8 = this.A0A;
        Modifier modifier = this.A07;
        boolean z9 = this.A0Y;
        String str2 = this.A0C;
        C81784oM r172 = r18;
        Modifier modifier2 = modifier;
        AnonymousClass7HD r19 = r56;
        KtCSuperShape0S3200000_I2 ktCSuperShape0S3200000_I22 = ktCSuperShape0S3200000_I2;
        C89935Hp r21 = r8;
        ImageUrl imageUrl2 = imageUrl;
        String str3 = str;
        String str4 = str2;
        AnonymousClass0ZU r30 = r15;
        AnonymousClass741.A00(A0H2, r172, modifier2, r19, ktCSuperShape0S3200000_I22, r21, imageUrl2, str3, str4, r25, r26, r27, r28, r29, r30, r12, r24, r17, r14, r13, this.A0M, this.A0Q, this.A0N, r11, r10, C115796vv.A00(this.A00), C115796vv.A01(this.A01), C115796vv.A01(this.A02), C115796vv.A01(this.A03), this.A04, this.A05, z, z2, z3, z4, z5, z6, z7, z8, z9);
        return Unit.A00;
    }
}
