package X;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/* renamed from: X.454  reason: invalid class name */
public final class AnonymousClass454 implements C82384pX {
    public final Map Aow() {
        C61153Sc[] r5 = new C61153Sc[79];
        System.arraycopy(new C61153Sc[]{C61153Sc.A00("Click To Messenger Ad", "click_to_messenger_ad.json", (String) null), C61153Sc.A00("Click to WhatsApp Ad", "stories_click_to_whatsapp_ad.json", (String) null), C61153Sc.A00("Click to Map (Get Directions) Ad", "open_map_cta_story_ad.json", (String) null), C61153Sc.A00("Visit IG Profile Ad", "ig_profile_visit_ad.json", (String) null), C61153Sc.A00("Mobile App Install (MAI) Ad", "mai_story_ad.json", (String) null), C61153Sc.A00("Canvas Ad", "canvas_ad.json", (String) null), C61153Sc.A00("Lead Ad", "lead_ad.json", (String) null), C61153Sc.A00("No CTA Ad", "no_cta.json", (String) null), C61153Sc.A00("Long Video (>= 16s) Ad", "longform_video.json", (String) null), C61153Sc.A00("Branded Content (Paid Partnership) Ad", "branded_content_ad.json", (String) null), C61153Sc.A00("Branded Content Long Video Ad", "branded_content_longform_video.json", (String) null), C61153Sc.A00("Branded Content Opt-In Carousel Ad", "branded_content_expandable_carousel.json", (String) null), C61153Sc.A00("Branded Content Long Video and Opt-In Carousel Ad", "branded_content_with_longform_video_and_expandable_carousel.json", (String) null), C61153Sc.A00("Political Ad", "political_ad.json", (String) null), C61153Sc.A00("Sensitive Vertical Ad", "sensitive_ad.json", (String) null), C61153Sc.A00("Disclaimer Text Ad", "reel_disclaimer_text_page_ad.json", (String) null), C61153Sc.A00("Disclaimer URL Ad", "reel_disclaimer_web_page_ad.json", (String) null), C61153Sc.A00("Video Ad with Subtitles", "video_ad_with_subtitles.json", (String) null), C61153Sc.A00("Polling Sticker Ad", "polling_sticker_ad.json", (String) null), C61153Sc.A00("Mention Sticker Ad", "story_ad_with_mention_sticker_and_branded_content.json", (String) null), C61153Sc.A00("Hashtag Sticker Ad", "story_ad_with_hashtag_sticker_and_branded_content.json", (String) null), C61153Sc.A00("Location Sticker Ad", "story_ad_with_location_sticker_and_branded_content.json", (String) null), C61153Sc.A00("Long CTA Text Ad", "long_cta_text_ad.json", (String) null), C61153Sc.A00("9:16 Single Image Ad", "single_media_916_image.json", (String) null), C61153Sc.A00("9:16 Carousel Image Ad", "three_part_mps_916.json", (String) null), C61153Sc.A00("Landscape Ad (Square Image)", "landscape_square_image_ad.json", (String) null), C61153Sc.A00("Landscape Ad (Landscape Image)", "landscape_landscape_image_ad.json", (String) null)}, 0, r5, 0, 27);
        System.arraycopy(new C61153Sc[]{C61153Sc.A00("Landscape Ad (Portrait Image)", "landscape_portrait_image_ad.json", (String) null), C61153Sc.A00("Landscape Ad (Video)", "landscape_video_ad.json", (String) null), C61153Sc.A00("Landscape Ad with Headline", "landscape_ad_with_headline.json", (String) null), C61153Sc.A00("Landscape Strong Font Caption Ad", "landscape_strong_font_caption.json", (String) null), C61153Sc.A00("Landscape Max 3 Lines Caption Ad", "landscape_max_3_lines_caption.json", (String) null), C61153Sc.A00("Landscape First Sentence Caption Ad", "landscape_first_sentence_caption_ad.json", (String) null), C61153Sc.A00("Landscape Multi Products Tag Ad", "story_ad_with_multi_products_tag.json", (String) null), C61153Sc.A00("Landscape With Keyword Highlight Ad", "landscape_keyword_highlight_caption.json", (String) null), C61153Sc.A00("Landscape With Center Text Alignment Ad", "landscape_center_text_alignment_caption.json", (String) null), C61153Sc.A00("Showreel Native Single Image Ad", "showreel_native_ad.json", (String) null), C61153Sc.A00("Showreel Native Single Image with Hashtag & Mention Ad", "showreel_native_caption_with_hashtag_and_mention.json", (String) null), C61153Sc.A00("Showreel Native Single Image with Non-English Hashtag Ad", "showreel_native_non_english_hashtag.json", (String) null), C61153Sc.A00("Showreel Native Long Caption Ad", "showreel_native_ad_with_more_caption.json", (String) null), C61153Sc.A00("Showreel Native Animated Ad", "showreel_native_animated_ad.json", (String) null), C61153Sc.A00("Showreel Native Animated with Hashtag & Mention Ad", "showreel_native_animated_with_hashtag_and_mention.json", (String) null), C61153Sc.A00("Showreel Native Carousel Image Ad", "showreel_native_carousel_ad.json", (String) null), C61153Sc.A00("Showreel Native DPA (Tesla) Ad", "showreel_native_dpa_tesla_template_ad.json", (String) null), C61153Sc.A00("Showreel Native DPA (Nicola) Ad", "showreel_native_dpa_nicolas_template_ad.json", (String) null), C61153Sc.A00("Showreel Composition Carousel Image Ad", "showreel_composition_carousel_ad.json", (String) null), C61153Sc.A00("Showreel Composition Image Ad", "showreel_composition_image_ad.json", (String) null), C61153Sc.A00("DPA Ad non 9:16", "dynamic_ad.json", (String) null), C61153Sc.A00("DPA Ad Smart Opt-In Carousel (3 cards)", "smarter_expandable_carousel_pos_3.json", (String) null), C61153Sc.A00("DPA Ad 9:16", "dpa_916_ad.json", (String) null), C61153Sc.A00("DPA Showcase Ad (Showreel Native)", "showreel_native_dpa_showcase_template_ad.json", (String) null), C61153Sc.A00("Collection Ad with Square Image", "collection_ad_square_image.json", (String) null), C61153Sc.A00("Collection Ad with Landscape Image", "collection_ad_landscape_image.json", (String) null), C61153Sc.A00("Collection Ad with Square Video", "collection_ad_square_video.json", (String) null)}, 0, r5, 27, 27);
        System.arraycopy(new C61153Sc[]{C61153Sc.A00("Collection Ad with Landscape Video", "collection_ad_landscape_video.json", (String) null), C61153Sc.A00("Collection Ad with List Template Canvas", "collection_ad_list_template.json", (String) null), C61153Sc.A00("Caption Card Landscape Image with Short Caption", "caption_card_no_crop_hashtag_and_mention.json", (String) null), C61153Sc.A00("Caption Card Landscape Image with Long Caption", "caption_card_no_crop_scrollable_text.json", (String) null), C61153Sc.A00("Caption Card 9:16 Image with Short Caption", "caption_card_cropped_hashtag_and_mention.json", (String) null), C61153Sc.A00("Caption Card Landscape Video", "caption_card_non916_video_hashtag_and_mention.json", (String) null), C61153Sc.A00("Caption Card 9:16 Video", "caption_card_916_video_hashtag_and_mention.json", (String) null), C61153Sc.A00("Video to Carousel (V2C) 3 Cards Ad", "video_to_carousel_ad.json", (String) null), C61153Sc.A00("Video to Carousel (V2C) 2 Cards Ad", "video_to_carousel_with_2cards.json", (String) null), C61153Sc.A00("Video to Carousel (V2C) Last Segment Long Video Ad", "video_to_carousel_last_segment_long_video.json", (String) null), C61153Sc.A00("End Scene Single Image Ad", "end_scene_image_ad.json", (String) null), C61153Sc.A00("End Scene Short (<16s) Video Ad", "end_scene_short_video_ad.json", (String) null), C61153Sc.A00("End Scene 1m Video Ad", "end_scene_60s_video_ad.json", (String) null), C61153Sc.A00("End Scene 1m Video to Carousel (V2C) 2 Card Ad", "video_to_carousel_with_2cards_end_scene.json", (String) null), C61153Sc.A00("Dynamic Duration Single Image Ad", "dynamic_duration_image_ad.json", (String) null), C61153Sc.A00("Dynamic Duration Carousel Image Ad", "dynamic_duration_carousel_image_ad.json", (String) null), C61153Sc.A00("Dynamic Duration Long Video Ad", "dynamic_duration_long_video_ad.json", (String) null), C61153Sc.A00("Dynamic Duration Long Video to Carousel Ad", "dynamic_duration_long_video_v2c_ad.json", (String) null), C61153Sc.A00("Generic Profile Card Combo Signals", "generic_profile_card_combo_signals.json", (String) null), C61153Sc.A00("Lead Gen Card Non 9:16 Gradient Background Small Sticker", "lead_gen_card_non9by16_gradient_small.json", (String) null), C61153Sc.A00("Auto Cropped Image Ad", "autocropped_landscape_ad_no_caption.json", (String) null), C61153Sc.A00("Auto Cropped Image Ad with Smart Caption", "autocropped_landscape_ad_with_smart_caption.json", (String) null), C61153Sc.A00("Auto Cropped Image Ad with First Sentence Caption", "autocropped_landscape_ad_with_first_caption.json", (String) null), C61153Sc.A00("9:16 Caption Ad", "9by16_ad_with_caption_area.json", (String) null), C61153Sc.A00("Retail Ad with Single ARTS (Square)", "retail_ad_with_single_arts_square_image.json", "retail_ad_with_single_arts_square_image")}, 0, r5, 54, 25);
        List<C61153Sc> A17 = C06750aI.A17(r5);
        ArrayList A0x = AnonymousClass0wJ.A0x(A17, 10);
        for (C61153Sc r2 : A17) {
            String str = r2.A01;
            if (str == null) {
                str = C18190wL.A0p(C81074n3.A07(r2.A00, ".", 0), 0);
            }
            A0x.add(new AnonymousClass4O1(AnonymousClass006.A01, str, AnonymousClass00U.A0L("stories_ads/", r2.A00), r2.A02));
        }
        LinkedHashMap A0v = C18190wL.A0v(AnonymousClass4WK.A0M(C02260Al.A0z(A0x, 10)));
        Iterator it = A0x.iterator();
        while (it.hasNext()) {
            AnonymousClass4O1.A00(A0v, it);
        }
        return A0v;
    }
}
