package X;

/* renamed from: X.0oz  reason: invalid class name and case insensitive filesystem */
public final class C14200oz {
    public static String A00(int i) {
        return i != 3 ? i != 4 ? i != 5 ? i != 6 ? i != 8 ? i != 9 ? i != 12 ? i != 13 ? i != 1412 ? i != 2470 ? i != 15755 ? "UNDEFINED_QPL_EVENT" : "REACTIONS_LITHO_UFI_REACTION_LIFECYCLE" : "REACTIONS_DYNAMIC_REACTIONS_DONWLOAD" : "REACTIONS_DYNAMIC_REACTIONS_UPDATE" : "REACTIONS_REACT_TO_COMMENT" : "REACTIONS_REACT_TO_POST" : "REACTIONS_LOAD_REACTORS_LIST_ON_SCROLL" : "REACTIONS_LOAD_REACTORS_LIST_TAB" : "REACTIONS_WAIT_TIME_REACTORS_LIST_CURRENT_TAB" : "REACTIONS_LOAD_REACTORS_LIST" : "REACTIONS_LOAD_INPUT_DOCK_COLD" : "REACTIONS_LOAD_INPUT_DOCK_WARM";
    }
}
