package X;

/* renamed from: X.0t4  reason: invalid class name and case insensitive filesystem */
public final class C16440t4 {
    public static String A00(int i) {
        return i != 1284 ? i != 1843 ? i != 2253 ? i != 4208 ? i != 8756 ? i != 10940 ? i != 11081 ? i != 11642 ? i != 13118 ? i != 13741 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_BACKUP_BACKUP" : "WEARABLE_BACKUP_REGISTER_LTE_BACKUP" : "WEARABLE_BACKUP_COLD_START" : "WEARABLE_BACKUP_AGGREGATE_BACKUP" : "WEARABLE_BACKUP_AGGREGATE_RESTORE" : "WEARABLE_BACKUP_UNREGISTER_PERIODIC_BACKUP" : "WEARABLE_BACKUP_RESTORE" : "WEARABLE_BACKUP_REGISTER_PERIODIC_BACKUP" : "WEARABLE_BACKUP_REGISTER_IMMEDIATE_BACKUP" : "WEARABLE_BACKUP_CANCEL_BACKUP";
    }
}
