package X;

import com.facebook.common.dextricks.DalvikInternals;

/* renamed from: X.0ud  reason: invalid class name and case insensitive filesystem */
public final class C17280ud {
    public static final AnonymousClass0RP A00 = new AnonymousClass0RP((byte) 10, 16);
    public static final AnonymousClass0RP A01 = new AnonymousClass0RP((byte) 10, 3);
    public static final AnonymousClass0RP A02 = new AnonymousClass0RP((byte) 11, 13);
    public static final AnonymousClass0RP A03 = new AnonymousClass0RP((byte) 10, 12);
    public static final AnonymousClass0RP A04 = new AnonymousClass0RP((byte) 3, 21);
    public static final AnonymousClass0RP A05 = new AnonymousClass0RP((byte) 11, 15);
    public static final AnonymousClass0RP A06 = new AnonymousClass0RP((byte) 11, 18);
    public static final AnonymousClass0RP A07 = new AnonymousClass0RP((byte) 11, 8);
    public static final AnonymousClass0RP A08 = new AnonymousClass0RP((byte) 11, 20);
    public static final AnonymousClass0RP A09 = new AnonymousClass0RP((byte) 10, 4);
    public static final AnonymousClass0RP A0A = new AnonymousClass0RP((byte) 10, 22);
    public static final AnonymousClass0RP A0B = new AnonymousClass0RP((byte) 11, 23);
    public static final AnonymousClass0RP A0C = new AnonymousClass0RP((byte) 11, 24);
    public static final AnonymousClass0RP A0D = new AnonymousClass0RP((byte) 11, 25);
    public static final AnonymousClass0RP A0E = new AnonymousClass0RP((byte) 2, 9);
    public static final AnonymousClass0RP A0F = new AnonymousClass0RP((byte) 10, 26);
    public static final AnonymousClass0RP A0G = new AnonymousClass0RP((byte) 2, 7);
    public static final AnonymousClass0RP A0H = new AnonymousClass0RP((byte) 8, 11);
    public static final AnonymousClass0RP A0I = new AnonymousClass0RP((byte) 8, 10);
    public static final AnonymousClass0RP A0J = new AnonymousClass0RP((byte) 2, 6);
    public static final AnonymousClass0RP A0K = new AnonymousClass0RP((byte) 2, 17);
    public static final AnonymousClass0RP A0L = new AnonymousClass0RP((byte) 8, 5);
    public static final AnonymousClass0RP A0M = new AnonymousClass0RP((byte) 11, 19);
    public static final AnonymousClass0RP A0N = new AnonymousClass0RP((byte) 15, 14);
    public static final AnonymousClass0RP A0O = new AnonymousClass0RP((byte) 11, 2);
    public static final AnonymousClass0RP A0P = new AnonymousClass0RP((byte) 10, 1);
    public static final AnonymousClass0RP A0Q = new AnonymousClass0RP((byte) 8, 2);
    public static final AnonymousClass0RP A0R = new AnonymousClass0RP((byte) 11, 3);
    public static final AnonymousClass0RP A0S = new AnonymousClass0RP((byte) 11, 1);
    public static final AnonymousClass0RP A0T = new AnonymousClass0RP(DalvikInternals.IOPRIO_CLASS_SHIFT, 10);
    public static final AnonymousClass0RP A0U = new AnonymousClass0RP((byte) 11, 1);
    public static final AnonymousClass0RP A0V = new AnonymousClass0RP((byte) 12, 4);
    public static final AnonymousClass0RP A0W = new AnonymousClass0RP((byte) 15, 8);
    public static final AnonymousClass0RP A0X = new AnonymousClass0RP((byte) 15, 6);
    public static final AnonymousClass0RP A0Y = new AnonymousClass0RP((byte) 11, 5);
    public static final AnonymousClass0RP A0Z = new AnonymousClass0RP((byte) 12, 11);
    public static final AnonymousClass0RP A0a = new AnonymousClass0RP((byte) 15, 7);
    public static final AnonymousClass0RP A0b = new AnonymousClass0RP((byte) 11, 13);
    public static final AnonymousClass0RP A0c = new AnonymousClass0RP((byte) 11, 3);
    public static final AnonymousClass0RP A0d = new AnonymousClass0RP((byte) 11, 2);
    public static final AnonymousClass0RP A0e = new AnonymousClass0RP((byte) 11, 9);
    public static final AnonymousClass0RP A0f = new AnonymousClass0RP((byte) 8, 4);
    public static final AnonymousClass0RP A0g = new AnonymousClass0RP((byte) 11, 8);
    public static final AnonymousClass0RP A0h = new AnonymousClass0RP((byte) 11, 9);
    public static final AnonymousClass0RP A0i = new AnonymousClass0RP((byte) 11, 5);
    public static final AnonymousClass0RP A0j = new AnonymousClass0RP((byte) 10, 11);
    public static final AnonymousClass0RP A0k = new AnonymousClass0RP((byte) 10, 2);
    public static final AnonymousClass0RP A0l = new AnonymousClass0RP((byte) 8, 3);
    public static final AnonymousClass0RP A0m = new AnonymousClass0RP((byte) 11, 10);
    public static final AnonymousClass0RP A0n = new AnonymousClass0RP((byte) 11, 6);
    public static final AnonymousClass0RP A0o = new AnonymousClass0RP((byte) 8, 7);
    public static final AnonymousClass0RP A0p = new AnonymousClass0RP((byte) 11, 1);
    public static final AnonymousClass0RP A0q = new AnonymousClass0RP((byte) 10, 12);
    public static final AnonymousClass0RP A0r = new AnonymousClass0RP((byte) 11, 3);
    public static final AnonymousClass0RP A0s = new AnonymousClass0RP((byte) 11, 1);
    public static final AnonymousClass0RP A0t = new AnonymousClass0RP((byte) 8, 2);
    public static final AnonymousClass0RP A0u = new AnonymousClass0RP((byte) 11, 2);
    public static final AnonymousClass0RP A0v = new AnonymousClass0RP((byte) 11, 1);
    public static final AnonymousClass0RP A0w = new AnonymousClass0RP((byte) 11, 3);
}
