package X;

/* renamed from: X.29w  reason: invalid class name and case insensitive filesystem */
public enum C320229w implements C021109v {
    ACL_CHECK_FAILURE(1),
    FETCH_FAILURE(2),
    FETCH_START(3),
    FETCH_SUCCESS(4),
    REPLICATED_STORAGE_INIT_APP_REMOVE_FAILURE(11),
    REPLICATED_STORAGE_INIT_APP_REMOVE_SENT(12),
    REPLICATED_STORAGE_INIT_APP_REMOVE_START(13),
    REPLICATED_STORAGE_INIT_APP_REMOVE_SUCCESS(14),
    REPLICATED_STORAGE_INIT_APP_SAVE_FAILURE(15),
    REPLICATED_STORAGE_INIT_APP_SAVE_SENT(16),
    REPLICATED_STORAGE_INIT_APP_SAVE_SUCCESS(18),
    REPLICATED_STORAGE_TARGET_APP_FETCH_FAILURE(19),
    REPLICATED_STORAGE_TARGET_APP_FETCH_START(20),
    REPLICATED_STORAGE_TARGET_APP_FETCH_SUCCESS(21),
    REPLICATED_STORAGE_TARGET_APP_REMOVE_FAILURE(22),
    REPLICATED_STORAGE_TARGET_APP_REMOVE_RECEIVED(23),
    REPLICATED_STORAGE_TARGET_APP_REMOVE_SUCCESS(24),
    REPLICATED_STORAGE_TARGET_APP_SAVE_FAILURE(25),
    REPLICATED_STORAGE_TARGET_APP_SAVE_RECEIVED(26),
    REPLICATED_STORAGE_TARGET_APP_SAVE_SUCCESS(27),
    TARGET_APP_FETCH_FAILURE(28),
    TARGET_APP_FETCH_SUCCESS(30),
    WRITE_FAILURE(8),
    WRITE_START(9),
    WRITE_SUCCESS(10);
    
    public final long A00;

    /* access modifiers changed from: public */
    C320229w(long j) {
        this.A00 = j;
    }
}
