package X;

import java.io.Serializable;
import org.webrtc.CameraVideoCapturer;

/* renamed from: X.4Nk  reason: invalid class name and case insensitive filesystem */
public final class C72304Nk implements Serializable {
    public double A00 = 0.0d;
    public double A01 = 2.0d;
    public double A02 = 1.2d;
    public double A03 = 0.0d;
    public double A04 = 0.0d;
    public double A05 = 0.0d;
    public double A06 = 1.0d;
    public double A07 = 2.0d;
    public double A08 = 1.2d;
    public double A09 = 2.0d;
    public double A0A = 0.0d;
    public double A0B = 0.0d;
    public double A0C = 1.0d;
    public int A0D = 0;
    public int A0E = 0;
    public int A0F = 0;
    public int A0G = 0;
    public int A0H = 0;
    public int A0I = 75;
    public int A0J = CameraVideoCapturer.CameraStatistics.CAMERA_OBSERVER_PERIOD_MS;
    public int A0K = 0;
    public int A0L = 65;
    public int A0M = 0;
    public boolean A0N = false;
    public boolean A0O = false;
    public boolean A0P = false;
    public boolean A0Q = false;
    public boolean A0R = false;
    public boolean A0S = false;
    public boolean A0T = false;
    public boolean A0U = false;
    public boolean A0V = false;
    public boolean A0W = true;
    public final float A0X;
    public final float A0Y;
    public final float A0Z;
    public final float A0a;
    public final float A0b;
    public final float A0c;
    public final float A0d;
    public final float A0e;
    public final float A0f;
    public final float A0g;
    public final float A0h;
    public final float A0i;
    public final float A0j;
    public final int A0k;
    public final int A0l;
    public final int A0m;
    public final int A0n;
    public final int A0o;
    public final int A0p;
    public final int A0q;
    public final int A0r;
    public final int A0s;
    public final int A0t;
    public final int A0u;
    public final int A0v;
    public final int A0w;
    public final int A0x;
    public final int A0y;
    public final int A0z;
    public final int A10;
    public final int A11;
    public final int A12;
    public final int A13;
    public final int A14;
    public final int A15;
    public final int A16;
    public final int A17;
    public final int A18;
    public final int A19;
    public final int A1A;
    public final int A1B;
    public final boolean A1C;
    public final boolean A1D;
    public final boolean A1E;
    public final boolean A1F;
    public final boolean A1G;
    public final boolean A1H;
    public final boolean A1I;
    public final boolean A1J;
    public final boolean A1K;
    public final boolean A1L;
    public final boolean A1M;
    public final boolean A1N;
    public final boolean A1O;
    public final boolean A1P;

    public C72304Nk(AnonymousClass3J1 r11) {
        this.A13 = r11.A0W;
        this.A14 = r11.A0X;
        this.A12 = r11.A0V;
        this.A11 = r11.A0U;
        this.A10 = r11.A0T;
        this.A0z = r11.A0S;
        this.A18 = r11.A0b;
        this.A19 = r11.A0c;
        this.A0l = r11.A0E;
        this.A1F = r11.A0i;
        this.A0j = r11.A0C;
        this.A1H = r11.A0k;
        this.A1L = r11.A0o;
        this.A0g = r11.A09;
        this.A0h = r11.A0A;
        this.A1G = r11.A0j;
        this.A1E = r11.A0h;
        this.A1D = r11.A0g;
        this.A1C = r11.A0f;
        this.A17 = r11.A0a;
        this.A1M = r11.A0p;
        this.A15 = r11.A0Y;
        this.A1B = r11.A0e;
        this.A1J = r11.A0m;
        this.A0X = r11.A00;
        this.A0Y = r11.A01;
        this.A0y = r11.A0R;
        this.A1A = r11.A0d;
        this.A1O = r11.A0r;
        this.A16 = r11.A0Z;
        this.A1K = r11.A0n;
        this.A1P = r11.A0s;
        this.A0i = r11.A0B;
        this.A1N = r11.A0q;
        this.A0t = r11.A0M;
        this.A0u = r11.A0N;
        this.A0s = r11.A0L;
        this.A0o = r11.A0H;
        this.A0q = r11.A0J;
        this.A0d = r11.A06;
        this.A0m = r11.A0F;
        this.A0n = r11.A0G;
        this.A0v = r11.A0O;
        this.A0w = r11.A0P;
        this.A0Z = r11.A02;
        this.A0a = r11.A03;
        this.A0p = r11.A0I;
        this.A1I = r11.A0l;
        this.A0e = r11.A07;
        this.A0f = r11.A08;
        this.A0k = r11.A0D;
        this.A0b = r11.A04;
        this.A0c = r11.A05;
        this.A0r = r11.A0K;
        this.A0x = r11.A0Q;
    }
}
