package com.facebookpay.form.cell.address;

import X.AnonymousClass0wJ;
import X.AnonymousClass3JE;
import X.C110616lz;
import X.C18180wK;
import X.C86124wJ;
import X.C86134wK;
import X.C91875gz;
import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.common.locale.Country;
import com.facebookpay.common.recyclerview.adapteritems.SelectionShippingAddressItem;
import com.facebookpay.form.cell.CellParams;
import com.facebookpay.form.model.AddressFormFieldsConfig;
import com.fbpay.logging.LoggingContext;
import com.google.common.collect.ImmutableList;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AddressCellParams extends CellParams {
    public static final Parcelable.Creator CREATOR = C86124wJ.A0X(41);
    public boolean A00;
    public boolean A01 = true;
    public final int A02;
    public final int A03;
    public final int A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final int A09;
    public final int A0A;
    public final int A0B;
    public final int A0C;
    public final Country A0D;
    public final AddressFormFieldsConfig A0E;
    public final LoggingContext A0F;
    public final ImmutableList A0G;
    public final ImmutableList A0H;
    public final String A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final String A0M;
    public final String A0N;
    public final String A0O;
    public final String A0P;
    public final List A0Q;
    public final Map A0R;
    public final boolean A0S;
    public final boolean A0T;
    public final boolean A0U;
    public final boolean A0V;
    public final boolean A0W;
    public final boolean A0X;
    public final String A0Y;

    public final int describeContents() {
        return 0;
    }

    public AddressCellParams(Parcel parcel) {
        super(parcel);
        this.A0I = parcel.readString();
        this.A0J = parcel.readString();
        this.A0L = parcel.readString();
        this.A0P = parcel.readString();
        this.A0K = parcel.readString();
        this.A0D = (Country) C18180wK.A0A(parcel, Country.class);
        this.A0M = parcel.readString();
        this.A0N = parcel.readString();
        this.A0O = parcel.readString();
        Parcelable A0A2 = C18180wK.A0A(parcel, AddressFormFieldsConfig.class);
        A0A2.getClass();
        this.A0E = (AddressFormFieldsConfig) A0A2;
        this.A0V = AnonymousClass3JE.A00(parcel);
        this.A05 = parcel.readInt();
        this.A06 = parcel.readInt();
        this.A09 = parcel.readInt();
        this.A0A = parcel.readInt();
        this.A07 = parcel.readInt();
        this.A0B = parcel.readInt();
        this.A03 = parcel.readInt();
        this.A08 = parcel.readInt();
        this.A0C = parcel.readInt();
        this.A04 = parcel.readInt();
        this.A0X = AnonymousClass3JE.A00(parcel);
        this.A0U = AnonymousClass3JE.A00(parcel);
        ArrayList A0v = AnonymousClass0wJ.A0v();
        Class<Integer> cls = Integer.class;
        C86134wK.A17(parcel, cls, A0v);
        this.A0H = ImmutableList.copyOf((Collection) A0v);
        this.A0Y = parcel.readString();
        this.A0R = parcel.readHashMap(HashMap.class.getClassLoader());
        this.A0W = AnonymousClass3JE.A00(parcel);
        this.A0F = (LoggingContext) C18180wK.A0A(parcel, LoggingContext.class);
        this.A01 = AnonymousClass3JE.A00(parcel);
        ArrayList A0v2 = AnonymousClass0wJ.A0v();
        this.A0Q = A0v2;
        C86134wK.A17(parcel, SelectionShippingAddressItem.class, A0v2);
        this.A00 = AnonymousClass3JE.A00(parcel);
        this.A02 = parcel.readInt();
        this.A0S = AnonymousClass3JE.A00(parcel);
        ArrayList A0v3 = AnonymousClass0wJ.A0v();
        C86134wK.A17(parcel, cls, A0v3);
        this.A0G = ImmutableList.copyOf((Collection) A0v3);
        this.A0T = AnonymousClass3JE.A00(parcel);
    }

    public final void writeToParcel(Parcel parcel, int i) {
        super.writeToParcel(parcel, i);
        parcel.writeString(this.A0I);
        parcel.writeString(this.A0J);
        parcel.writeString(this.A0L);
        parcel.writeString(this.A0P);
        parcel.writeString(this.A0K);
        parcel.writeParcelable(this.A0D, i);
        parcel.writeString(this.A0M);
        parcel.writeString(this.A0N);
        parcel.writeString(this.A0O);
        parcel.writeParcelable(this.A0E, i);
        parcel.writeInt(this.A0V ? 1 : 0);
        parcel.writeInt(this.A05);
        parcel.writeInt(this.A06);
        parcel.writeInt(this.A09);
        parcel.writeInt(this.A0A);
        parcel.writeInt(this.A07);
        parcel.writeInt(this.A0B);
        parcel.writeInt(this.A03);
        parcel.writeInt(this.A08);
        parcel.writeInt(this.A0C);
        parcel.writeInt(this.A04);
        parcel.writeInt(this.A0X ? 1 : 0);
        parcel.writeInt(this.A0U ? 1 : 0);
        parcel.writeList(this.A0H);
        parcel.writeString(this.A0Y);
        parcel.writeMap(this.A0R);
        parcel.writeInt(this.A0W ? 1 : 0);
        parcel.writeParcelable(this.A0F, i);
        parcel.writeInt(this.A01 ? 1 : 0);
        parcel.writeList(this.A0Q);
        parcel.writeInt(this.A00 ? 1 : 0);
        parcel.writeInt(this.A02);
        parcel.writeInt(this.A0S ? 1 : 0);
        parcel.writeList(this.A0G);
        parcel.writeInt(this.A0T ? 1 : 0);
    }

    public AddressCellParams(C91875gz r2) {
        super((C110616lz) r2);
        this.A0I = r2.A0F;
        this.A0J = r2.A0G;
        this.A0L = r2.A0I;
        this.A0P = null;
        this.A0K = r2.A0H;
        this.A0D = r2.A0B;
        this.A0M = r2.A0J;
        this.A0N = r2.A0K;
        this.A0O = r2.A0L;
        this.A0E = r2.A0X;
        this.A0V = r2.A0T;
        this.A05 = r2.A03;
        this.A06 = r2.A04;
        this.A09 = r2.A07;
        this.A0A = r2.A08;
        this.A07 = r2.A05;
        this.A0B = r2.A09;
        this.A03 = r2.A01;
        this.A08 = r2.A06;
        this.A0C = r2.A0A;
        this.A04 = r2.A02;
        this.A0X = r2.A0W;
        this.A0U = r2.A0S;
        this.A0H = r2.A0E;
        this.A0Y = r2.A0M;
        this.A0R = r2.A0O;
        this.A0W = r2.A0U;
        this.A0F = r2.A0C;
        this.A01 = r2.A0V;
        this.A0Q = r2.A0N;
        this.A00 = r2.A0Q;
        this.A02 = r2.A00;
        this.A0S = r2.A0P;
        this.A0G = r2.A0D;
        this.A0T = r2.A0R;
    }
}
